# Generated by Django 4.2.5 on 2023-09-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaysOfTheWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('enrollment_cap', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('subject', models.CharField(choices=[('SCI', 'Science'), ('HIS', 'History'), ('SOC', 'Social Studies'), ('MATH', 'Mathematics'), ('ENG', 'English'), ('CS', 'Computer Science'), ('ART', 'Arts')], default='SCI', max_length=4)),
                ('days', models.ManyToManyField(to='main_app.daysoftheweek')),
            ],
        ),
    ]
