# Generated by Django 4.2.5 on 2023-09-22 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrollment_cap',
        ),
        migrations.RemoveField(
            model_name='course',
            name='password',
        ),
        migrations.RemoveField(
            model_name='course',
            name='require_password',
        ),
    ]
