# Generated by Django 4.2.5 on 2023-09-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_course_enrollment_cap_remove_course_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
